import type { ThemeDefinition } from 'vuetify'

// Industrial console palette: Precision Mining Blue carries primary actions and live telemetry;
// Deep Slate/Navy is the structural foundation (surfaces, secondary accents); Safety Amber/Red
// are reserved for warning/critical states only — they are never used for primary UI chrome.
export const staticPrimaryColor = '#1565C0'
export const staticPrimaryDarkenColor = '#0D47A1'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      'primary-light': '#5E92F3',
      'secondary': '#334155',
      'on-secondary': '#fff',
      'secondary-darken-1': '#1E293B',
      'secondary-light': '#64748B',
      'success': '#56CA00',
      'on-success': '#fff',
      'success-darken-1': '#4CAF00',
      'success-light': '#76D92D',
      'info': '#03C3EC',
      'on-info': '#fff',
      'info-darken-1': '#03AFD4',
      'info-light': '#35CFF0',
      'warning': '#FFB400',
      'on-warning': '#fff',
      'warning-darken-1': '#E6A200',
      'warning-light': '#FFC633',
      'error': '#D32F2F',
      'on-error': '#fff',
      'error-darken-1': '#B71C1C',
      'error-light': '#EF5350',
      'background': '#F1F5F9',
      'on-background': '#1E293B',
      'surface': '#fff',
      'on-surface': '#1E293B',
      'grey-50': '#F8FAFC',
      'grey-100': '#F1F5F9',
      'grey-200': '#E2E8F0',
      'grey-300': '#CBD5E1',
      'grey-400': '#94A3B8',
      'grey-500': '#64748B',
      'grey-600': '#475569',
      'grey-700': '#334155',
      'grey-800': '#1E293B',
      'grey-900': '#0F172A',
      'grey-light': '#F8FAFC',
      'perfect-scrollbar-thumb': '#CBD5E1',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#F8FAFC',
    },

    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#1E293B',
      'tooltip-background': '#1E293B',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#1E293B',
      'border-opacity': 0.12,
      'table-header-color': '#FFFFFF',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#EEF1F3',
      'chat-bg': '#F7F8F8',

      // Shadows
      'shadow-key-umbra-color': '#1E293B',
      'shadow-xs-opacity': 0.06,
      'shadow-sm-opacity': 0.08,
      'shadow-md-opacity': 0.10,
      'shadow-lg-opacity': 0.14,
      'shadow-xl-opacity': 0.18,
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': '#3B82F6',
      'on-primary': '#fff',
      'primary-darken-1': '#2563EB',
      'primary-light': '#93C5FD',
      'secondary': '#64748B',
      'on-secondary': '#fff',
      'secondary-darken-1': '#475569',
      'secondary-light': '#94A3B8',
      'success': '#56CA00',
      'on-success': '#fff',
      'success-darken-1': '#4CAF00',
      'success-light': '#76D92D',
      'info': '#03C3EC',
      'on-info': '#fff',
      'info-darken-1': '#03AFD4',
      'info-light': '#35CFF0',
      'warning': '#FFB400',
      'on-warning': '#fff',
      'warning-darken-1': '#E6A200',
      'warning-light': '#FFC633',
      'error': '#EF5350',
      'on-error': '#fff',
      'error-darken-1': '#D32F2F',
      'error-light': '#FF8A80',
      'background': '#0F172A',
      'on-background': '#E2E8F0',
      'surface': '#1E293B',
      'on-surface': '#E2E8F0',
      'grey-50': '#1E293B',
      'grey-100': '#273449',
      'grey-200': '#334155',
      'grey-300': '#475569',
      'grey-400': '#64748B',
      'grey-500': '#94A3B8',
      'grey-600': '#AAB3DE',
      'grey-700': '#CBD5E1',
      'grey-800': '#E2E8F0',
      'grey-900': '#F1F5F9',
      'grey-light': '#273449',
      'perfect-scrollbar-thumb': '#334155',
      'skin-bordered-background': '#1E293B',
      'skin-bordered-surface': '#1E293B',
    },
    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#020617',
      'tooltip-background': '#E2E8F0',
      'overlay-scrim-opacity': 0.6,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#E2E8F0',
      'border-opacity': 0.12,
      'table-header-color': '#1E293B',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#334155',
      'chat-bg': '#16213A',

      // Shadows
      'shadow-key-umbra-color': '#020617',
      'shadow-xs-opacity': 0.18,
      'shadow-sm-opacity': 0.20,
      'shadow-md-opacity': 0.22,
      'shadow-lg-opacity': 0.24,
      'shadow-xl-opacity': 0.26,
    },
  },
}

export default themes
